### ISSUE TITLE
RHEL7 DevAssistant 0.11.2

### ISSUE THREAD

**Issue by davidjkenner** [forge/devassistant-addon#1]
I have RHEL7 and installed DevAssistant 0.11.2 and am able to run basic commands with it.  I also have JBoss Studio 11.1.0.GA installed.  I tried the following:

Launch Forge Console 
ran the following command:
[workspace]$ addon-install-from-git --url https://github.com/forge/devassistant-addon.git

I get the following error:
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.786 s
[INFO] Finished at: 2018-01-05T17:14:07-05:00
[INFO] Final Memory: 182M/529M
[INFO] ------------------------------------------------------------------------
***ERROR*** Error while executing 'addon-install-from-git'
java.lang.RuntimeException: Could not resolve build directory for project [/tmp/tmpdir4219536316773509480/pom.xml]
	at org.jboss.forge.addon.maven.projects.facets.MavenPackagingFacet.getFinalArtifact(MavenPackagingFacet.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.maven.projects.facets.MavenPackagingFacet_$$_javassist_14123f73-9578-40b1-becf-f9010e6b87d3.getFinalArtifact(MavenPackagingFacet_$$_javassist_14123f73-9578-40b1-becf-f9010e6b87d3.java)
	at org.jboss.forge.addon.maven.projects.MavenProjectBuilder.build(MavenProjectBuilder.java:114)
	at org.jboss.forge.addon.manager.impl.ui.AddonGitBuildAndInstallCommand.execute(AddonGitBuildAndInstallCommand.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor$1.call(ClassLoaderInterceptor.java:87)
	at org.jboss.forge.furnace.util.ClassLoaders.executeIn(ClassLoaders.java:42)
	at org.jboss.forge.furnace.proxy.ClassLoaderInterceptor.invoke(ClassLoaderInterceptor.java:103)
	at org.jboss.forge.addon.manager.impl.ui.AddonGitBuildAndInstallCommand_$$_javassist_819eed45-2c8c-45f0-97e5-2cb9175ca629.execute(AddonGitBuildAndInstallCommand_$$_javassist_819eed45-2c8c-45f0-97e5-2cb9175ca629.java)
	at org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.execute(SingleCommandControllerImpl.java:94)
	at org.jboss.forge.addon.shell.aesh.CommandAdapter.execute(CommandAdapter.java:97)
	at org.jboss.forge.addon.shell.aesh.ForgeCommandContainer.executeCommand(ForgeCommandContainer.java:88)
	at org.jboss.aesh.console.AeshConsoleImpl$AeshConsoleCallbackImpl.execute(AeshConsoleImpl.java:311)
	at org.jboss.aesh.console.AeshProcess.run(AeshProcess.java:53)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)

**Comment by gastaldi** [comment]
I updated the pom.xml to use a more recent version. Can you try again?
